function [rotmat] = rotation_matrix(axis,theta)

switch axis
    case 'x'
        rotmat = sparse([       1           0             0; ...
                         0       cos(theta)    -sin(theta); ...
                         0       sin(theta)     cos(theta)]);
    case 'y'
        rotmat = sparse([   cos(theta)      0          sin(theta); ...
                         0           1             0; ...
                    -sin(theta)      0          cos(theta)]);
    case 'z'
        rotmat = sparse([   cos(theta)  -sin(theta)       0; ...
                     sin(theta)   cos(theta)       0; ...
                         0           0             1]);
end
